name: Package

on:
    workflow_dispatch:
    push:

jobs:
  build:
    name: Build package
    environment: anaconda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.34
      with:
          recipe-path: "recipe.yaml"
          build-args: --experimental
    - name: Upload to anaconda
      run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload anaconda -o $ANACONDA_OWNER -c main "$pkg" --force
          done
      env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
          ANACONDA_OWNER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_CHANNEL: ${{ secrets.ANACONDA_USER }}
